# Generated by Django 6.0.3 on 2026-06-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0002_section_strand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviser_assignments', to='enrollment.academicyear')),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviser_sections', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adviser_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adviser_assignment', to='enrollment.section')),
            ],
            options={
                'db_table': 'headteacher_adviser_assignments',
                'ordering': ['section__name'],
                'indexes': [models.Index(fields=['academic_year', 'adviser'], name='headteacher_academi_7b002e_idx')],
            },
        ),
    ]
