# Generated by Django 6.0.5 on 2026-05-23 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_graderecord_encoded_by'),
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(blank=True, help_text='Leave blank to include all grade levels in the academic year.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='enrollment.academicyear')),
                ('section', models.ForeignKey(blank=True, help_text='Leave blank to include all sections for the grade level.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='enrollment.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers_assignments',
                'indexes': [models.Index(fields=['teacher', 'academic_year'], name='teachers_as_teacher_57183f_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject', 'academic_year', 'grade_level', 'section'), name='unique_teacher_assignment_scope')],
            },
        ),
    ]
