# Generated by Django 6.0.3 on 2026-06-27 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('students', '0003_studentloginlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_course', models.CharField(max_length=128)),
                ('strand', models.CharField(blank=True, max_length=64)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommendation_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('explanation', models.TextField(blank=True)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('trend', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(db_index=True, default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_recommendations', to='enrollment.academicyear')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_recommendations', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_recommendations', to='enrollment.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_recommendations', to='students.studentprofile')),
            ],
            options={
                'db_table': 'recommendations_course',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['student', 'is_latest'], name='recommendat_student_f63cf8_idx'), models.Index(fields=['academic_year', 'section'], name='recommendat_academi_cddd43_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'version'), name='unique_recommendation_version_per_student')],
            },
        ),
    ]
