# Generated by Django 6.0.3 on 2026-06-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, help_text='Snapshot of the acting user (kept even if the user is deleted).', max_length=150)),
                ('module', models.CharField(choices=[('profile', 'Profile Update'), ('grade_encoding', 'Grade Encoding'), ('grade_approval', 'Grade Approval'), ('section_creation', 'Section Creation'), ('teacher_assignment', 'Subject Teacher Assignment'), ('adviser_assignment', 'Adviser Assignment'), ('recommendation', 'Recommendation Generation'), ('forecast', 'Enrollment Forecast Generation'), ('enrollment', 'Enrollment Decision')], db_index=True, max_length=32)),
                ('action', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_trail',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'created_at'], name='audit_trail_module_1f7995_idx')],
            },
        ),
    ]
