# Generated by Django 6.0.3 on 2026-06-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('adviser', 'Adviser'), ('head_teacher', 'Head Teacher'), ('registrar', 'Registrar'), ('admin', 'Admin')], db_index=True, default='student', max_length=20),
        ),
    ]
