import React, { useState } from 'react';
import { SectionHead, Badge, EmptyState } from '../common/Cards';
import {
  getAssignmentHistory,
  getValidationHistory,
  getSectionCreations,
  getForecastHistory
} from './headteacherApi';
import '../common/common.css';
import './AuditTrails.css';

const STATUS_VARIANT = { approved: 'success', pending: 'warning', rejected: 'danger' };

const AuditTrails = () => {
  const assignments = getAssignmentHistory();
  const adviserAssignments = assignments.filter((a) => a.type === 'Adviser');
  const subjectAssignments = assignments.filter((a) => a.type === 'Subject Teacher');
  const sectionCreations = getSectionCreations();
  const validations = getValidationHistory();
  const forecasts = getForecastHistory();

  const CATEGORIES = [
    {
      id: 'adviser',
      icon: '🧑‍🏫',
      title: 'Adviser Assignments',
      count: adviserAssignments.length,
      items: adviserAssignments.map((a) => ({
        primary: a.who,
        secondary: `Assigned to ${a.section}`,
        meta: a.date
      }))
    },
    {
      id: 'subject',
      icon: '🗂️',
      title: 'Subject Teacher Assignments',
      count: subjectAssignments.length,
      items: subjectAssignments.map((a) => ({
        primary: a.who,
        secondary: `${a.subject} · ${a.section}`,
        meta: a.date
      }))
    },
    {
      id: 'section',
      icon: '🏫',
      title: 'Section Creation',
      count: sectionCreations.length,
      items: sectionCreations.map((s) => ({
        primary: s.name,
        secondary: `${s.strand} · ${s.totalStudents} students`,
        meta: s.date
      }))
    },
    {
      id: 'validation',
      icon: '✅',
      title: 'Grade Validation',
      count: validations.length,
      items: validations.map((v) => ({
        primary: v.student,
        secondary: v.subject,
        meta: v.validatedAt || v.submittedAt,
        badge: v.status
      }))
    },
    {
      id: 'forecast',
      icon: '📈',
      title: 'Enrollment Forecast Generation',
      count: forecasts.length,
      items: forecasts.map((f) => ({
        primary: f.label,
        secondary: `Generated by ${f.generatedBy}`,
        meta: f.date
      }))
    }
  ];

  const [active, setActive] = useState(CATEGORIES[0].id);
  const activeCategory = CATEGORIES.find((c) => c.id === active) || CATEGORIES[0];

  return (
    <div className="rd-section">
      <SectionHead title="Audit Trails" subtitle="Organized activity history across all head-teacher actions." />

      <div className="gp-grid is-tight at-cards">
        {CATEGORIES.map((c) => (
          <button
            key={c.id}
            type="button"
            className={`gp-card at-card ${active === c.id ? 'is-active' : ''}`}
            onClick={() => setActive(c.id)}
          >
            <span className="at-card-icon" aria-hidden="true">{c.icon}</span>
            <span className="at-card-title">{c.title}</span>
            <span className="at-card-count">{c.count} record{c.count === 1 ? '' : 's'}</span>
          </button>
        ))}
      </div>

      <div className="gp-card at-detail">
        <div className="gp-card-title">
          <span className="gp-card-icon" aria-hidden="true">{activeCategory.icon}</span>
          {activeCategory.title}
        </div>
        {activeCategory.items.length === 0 ? (
          <EmptyState icon="🗂️" title="No records yet" message="Activity in this category will appear here." />
        ) : (
          <ul className="at-list">
            {activeCategory.items.map((item, i) => (
              <li key={i} className="at-item">
                <div className="at-item-main">
                  <span className="at-item-primary">{item.primary}</span>
                  <span className="at-item-secondary">{item.secondary}</span>
                </div>
                <div className="at-item-side">
                  {item.badge ? <Badge variant={STATUS_VARIANT[item.badge]}>{item.badge}</Badge> : null}
                  <span className="at-item-meta">{item.meta}</span>
                </div>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
};

export default AuditTrails;
