# Generated by Django 6.0.3 on 2026-06-04 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Home address')),
                ('profession', models.CharField(blank=True, help_text='Parent profession (optional)', max_length=100)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact name', max_length=100)),
                ('emergency_phone', models.CharField(blank=True, help_text='Emergency contact number', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this parent account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parents_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='parents_pro_user_id_f99b45_idx')],
            },
        ),
    ]
