# Generated by Django 6.0.5 on 2026-09-17 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the login request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent (browser/device info)')),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to='parents.parentprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parents_login_logs',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', 'login_time'], name='parents_log_user_id_cfa618_idx')],
            },
        ),
    ]
