# Generated by Django 6.0.3 on 2026-06-04 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_profile_persistence_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the login request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent (browser/device info)')),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='students.studentprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students_login_logs',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['student', 'login_time'], name='students_lo_student_b1d1e4_idx'), models.Index(fields=['user', 'login_time'], name='students_lo_user_id_2bd6d7_idx')],
            },
        ),
    ]
