# Generated by Django 6.0.5 on 2026-05-23 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. 2025-2026', max_length=9, unique=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enrollment_academic_years',
                'ordering': ['-label'],
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'enrollment_strands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('grade_level', models.CharField(blank=True, max_length=32)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='enrollment.academicyear')),
            ],
            options={
                'db_table': 'enrollment_sections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lrn', models.CharField(db_index=True, max_length=32)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('grade_level_enrollment', models.CharField(db_index=True, max_length=32)),
                ('grade_level_current', models.CharField(blank=True, max_length=32)),
                ('registrar_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('admin_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('submitted_info', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parent_consent', models.BooleanField(default=False)),
                ('parent_consent_by', models.CharField(blank=True, max_length=150)),
                ('parent_consent_at', models.DateTimeField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=32)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='enrollment.academicyear')),
                ('reviewed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_registrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrar_reviews', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='enrollment.section')),
                ('strand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='enrollment.strand')),
            ],
            options={
                'db_table': 'enrollment_applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['academic_year', 'name'], name='enrollment__academi_b1b389_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_section_per_year'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['academic_year', 'registrar_status'], name='enrollment__academi_adbff1_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['academic_year', 'admin_status'], name='enrollment__academi_66781a_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['lrn'], name='enrollment__lrn_77d505_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('lrn', 'academic_year'), name='unique_lrn_per_academic_year'),
        ),
    ]
