# Generated by Django 6.0.5 on 2026-09-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_section_strand'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided when rejected by the registrar or admin.'),
        ),
    ]
